用户 1 推送代码到远端

```shell
git add .
git commit -m '用户1修改的代码'
git push
```

用户 2 修改远程仓库中的代码

```shell
git fetch
# 修改别人提交的代码后
git add .
git commit -m '用户2修改后的代码'
git push
```

此时会出现冲突

```shell
error: failed to push some refs to 'https://github.com /.../test-demo.git'
```

```shell
git branch -av # 查看远端分支
git merge origin/test # 输入 merge 的信息
git push # 现在可以成功推送代码了
```

